services:
  autotests:
    image: bi_tests:latest
    build:
      dockerfile: .tools/Dockerfile
    volumes:
      - .:/autotests
    command: npx playwright test -g Smoke | ln s /node_modulse ./node_modules && npx playwright test -g Smoke
