services:
  autotests:
    image: bi_tests:latest
    build:
      context: .
      dockerfile: .tools/Dockerfile
    volumes:
      - .:/autotests
      - ./test-results:/autotests/test-results
      - ./.temp:/autotests/.temp
    environment:
      - WORKERS_COUNT
      - BI_URL
      - BI_USERNAME
      - BI_PASSWORD
      - BI_USER_ID
      - AD_USERNAME
      - AD_PASSWORD
      - AD_HOST
      - AD_PORT
      - AD_DOMEN
    command: /bin/sh -c 'npx playwright test --project="Smoke 1.32 Chromium"; npx playwright test --project="API Tests 32"'
