import { APIResponse } from '@playwright/test';
import test from '@playwright/test';

let response: APIResponse;
const path = '/api/v0/settings';

test(`Проверка POST ${path}`, async ({ request }) => {
  await test.step('401', async () => {
    response = await request.post(path, {
      data: {
        passwordpolicy: {
          settings: {
            RequiredLength: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            RequireNonAlphanumeric: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            RequireLowercase: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            RequireUppercase: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            RequireDigit: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            PasswordLifetime: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        securitylogs: {
          settings: {
            SecurityLogsLifetime: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            MaxTableSize: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            MaxFileCefSize: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            Emails: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            AlertThreshold: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        adlogin: {
          settings: {
            EnableAdLogin: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        cartography: {
          settings: {
            tileLayerUrl: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        failedaccess: {
          settings: {
            Enabled: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            FailedAccessCount: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            FailedAccessAction: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            BlockedOnSettings: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        tokenlifetime: {
          settings: {
            InactivityTime: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            TokenLifeTime: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        gpt: {
          settings: {
            Enabled: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            apiKey: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            GPTType: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            modelGpt: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            dirIdYandex: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            modelYandex: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        smtp: {
          settings: {
            Enabled: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            server: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            port: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            login: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            password: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            from: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            fromName: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            useSsl: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            useTls: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
            disableSslValidation: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        loadwindowsize: {
          settings: {
            LoadWindowSize: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        loginpage: {
          settings: {
            DisplaySlider: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
        backgroundprocess: {
          settings: {
            BackgroundProcessesStorageTimeInDays: {
              value: 'string',
              title: 'string',
              required: 'string',
              type: 'string',
              isOptional: 'string',
              min: 'string',
              max: 'string',
              isMulti: 'string',
              options: [
                {
                  value: 'string',
                  title: 'string',
                  required: 'string',
                  isSelected: 'string',
                },
              ],
              showOn: 'string',
              warning: 'string',
              hint: 'string',
              key: 'string',
            },
          },
        },
      },
    });

    const status = response.status();
    if (status !== 401) {
      throw Error('Ожидаемый статус: 401. Полученный статус запроса: ' + status);
    }
  });
});
