# .github/workflows/actions.yml
name: PIX BI Smoke Tests
on:
  push:
    branches: [bi_1.32]
  pull_request:
    branches: [bi_1.32]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      WORKERS_COUNT: ${{ vars.WORKERS_COUNT }}
      BI_URL: ${{ secrets.BI_URL }}
      BI_USERNAME: ${{ secrets.BI_USERNAME }}
      BI_PASSWORD: ${{ secrets.BI_PASSWORD }}
      BI_USER_ID: ${{ secrets.BI_USER_ID }}
      AD_USERNAME: ${{ secrets.AD_USERNAME }}
      AD_PASSWORD: ${{ secrets.AD_PASSWORD }}
      AD_HOST: ${{ secrets.AD_HOST }}
      AD_PORT: ${{ secrets.AD_PORT }}
      AD_DOMEN: ${{ secrets.AD_DOMEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build autotests image
        run: docker compose build autotests

      - name: Run Smoke Tests
        run: docker compose run --rm autotests

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            .temp/
          retention-days: 3
